import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProviders from "./components/ReactQueryProvider";
import { Inter, Nanum_Gothic } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const ng = Nanum_Gothic({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
